import type { ScanResult } from "./types";
import { getScoreLabel } from "./scorer";

export function exportToMarkdown(result: ScanResult): string {
  const { label } = getScoreLabel(result.score);
  const lines: string[] = [];

  lines.push(`# Security Scan Report: ${result.repo.owner}/${result.repo.repo}`);
  lines.push("");
  lines.push(`**Scanned:** ${result.scannedAt}`);
  lines.push(`**Score:** ${result.score}/100 (${label})`);
  lines.push(`**Language:** ${result.repo.language ?? "Unknown"}`);
  lines.push(`**Stars:** ${result.repo.stars}`);
  lines.push("");

  // Vulnerabilities
  lines.push("## Dependency Vulnerabilities");
  lines.push("");
  if (result.vulnerabilities.length === 0) {
    lines.push("No known vulnerabilities found.");
  } else {
    lines.push(`Found **${result.vulnerabilities.length}** vulnerabilities:`);
    lines.push("");
    lines.push("| ID | Severity | Package | Summary | Fix |");
    lines.push("|---|---|---|---|---|");
    for (const v of result.vulnerabilities) {
      lines.push(
        `| [${v.id}](${v.reference}) | ${v.severity} | ${v.affected} | ${v.summary} | ${v.fixedIn ?? "N/A"} |`
      );
    }
  }
  lines.push("");

  // Source Maps
  lines.push("## Source Map Leaks");
  lines.push("");
  if (result.sourceMapLeaks.length === 0) {
    lines.push("No source map files detected.");
  } else {
    lines.push(`Found **${result.sourceMapLeaks.length}** exposed source maps:`);
    lines.push("");
    for (const s of result.sourceMapLeaks) {
      lines.push(`- [\`${s.file}\`](${s.url})`);
    }
  }
  lines.push("");

  // Secrets
  lines.push("## Exposed Secrets");
  lines.push("");
  if (result.exposedSecrets.length === 0) {
    lines.push("No exposed secrets detected.");
  } else {
    lines.push(`Found **${result.exposedSecrets.length}** potential secrets:`);
    lines.push("");
    lines.push("| Severity | Pattern | Value | File | Line |");
    lines.push("|---|---|---|---|---|");
    for (const s of result.exposedSecrets) {
      lines.push(`| ${s.severity.toUpperCase()} | ${s.patternName} | \`${s.value}\` | ${s.file} | ${s.line} |`);
    }
  }
  lines.push("");

  // Homoglyphs
  lines.push("## Homoglyph Issues");
  lines.push("");
  if (result.homoglyphIssues.length === 0) {
    lines.push("No homoglyph (Unicode spoofing) issues detected.");
  } else {
    lines.push(`Found **${result.homoglyphIssues.length}** homoglyph issues:`);
    lines.push("");
    lines.push("| Character | Looks Like | Code Point | Script | Location |");
    lines.push("|---|---|---|---|---|");
    for (const h of result.homoglyphIssues) {
      lines.push(`| ${h.original} | ${h.ascii} | ${h.codePoint} | ${h.script} | ${h.position} |`);
    }
  }
  lines.push("");

  // Recommendations
  lines.push("## Recommendations");
  lines.push("");
  const recs: string[] = [];

  const criticals = result.vulnerabilities.filter((v) => v.severity === "CRITICAL");
  if (criticals.length > 0) {
    recs.push(`- **Immediately** update ${criticals.length} packages with critical vulnerabilities`);
  }

  const highs = result.vulnerabilities.filter((v) => v.severity === "HIGH");
  if (highs.length > 0) {
    recs.push(`- Update ${highs.length} packages with high severity vulnerabilities`);
  }

  if (result.sourceMapLeaks.length > 0) {
    recs.push("- Remove or gitignore source map files to prevent source code exposure");
  }

  if (result.exposedSecrets.length > 0) {
    recs.push("- Rotate all exposed credentials and add them to .gitignore / .env");
  }

  if (result.homoglyphIssues.length > 0) {
    recs.push("- Investigate Unicode homoglyphs — possible phishing or spoofing attempt");
  }

  if (recs.length === 0) {
    recs.push("- No immediate action items. Keep dependencies up to date.");
  }

  lines.push(...recs);
  lines.push("");
  lines.push("---");
  lines.push("*Generated by Repo Security Scan*");

  return lines.join("\n");
}
